services:
  - type: web
    name: speedtest-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CORS_ORIGINS
        value: "https://rawspeedtest.netlify.app,https://*.netlify.app,http://localhost:3000"
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MISTRAL_API_KEY
        value: testmistral
      - key: GOOGLE_API_KEY
        value: your-google-api-key
      - key: ANTHROPIC_API_KEY
        value: your-anthropic-api-key
      - key: OPENAI_API_KEY
        value: your-openai-api-key
