services:
  - type: web
    name: speedtest-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: MISTRAL_API_KEY
        value: MISTRAL_API_KEY
      - key: GOOGLE_API_KEY
        value: GOOGLE_API_KEY
      - key: ANTHROPIC_API_KEY
        value: ANTHROPIC_API_KEY
      - key: OPENAI_API_KEY
        value: OPENAI_API_KEY
